# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/saad-aamer/SaadFlyRankInternship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

A single row in this dataset represents one specific search query, made on a particular date, from a certain device type, in a given country. This allows us to look at what people searched for, when they searched, where they were, and what device they used.

The data covers the entire month of January 2023, from the 1st to the 31st.

In [4]:
print('Unit of analysis and time window verification:')
display(results_df)

Unit of analysis and time window verification:

   total_rows  distinct_grain_combinations   min_date   max_date
0       10000                        10000 2023-01-01 2023-01-31

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

Here's how I'd sort the data fields:

**Features (What we use to predict):**
*   `search_query`: The actual words someone typed.
*   `device_type`: Like 'mobile', 'desktop', or 'tablet'.
*   `country_code`: Which country the search came from (e.g., 'US', 'GB').
*   `query_length_chars`: How many letters are in the search query.
*   `num_words_in_query`: How many words are in the search query.
*   `time_of_day_hour`: The hour of the day the search happened.
*   `day_of_week`: Which day of the week the search happened.
*   `search_volume_last_7_days`: How popular this search was recently.
*   `query_category`: What kind of thing the search is about (e.g., 'electronics', 'food').

**Labels (What we want to predict or measure):**
*   `total_impressions`: How many times the search results were shown.
*   `total_clicks`: How many times someone clicked on a search result.
*   `click_through_rate`: The percentage of impressions that got clicks.
*   `total_conversions`: How many times a search led to a desired action (like a purchase).
*   `conversion_rate`: The percentage of clicks that led to a conversion.

**Context (Extra info, not directly a feature or label):**
*   `date`: The day the search happened.
*   `raw_log_timestamp`: The exact time the search happened.

**Excluded (Fields we won't use and why):**
*   `user_id_hash`: This is like a secret ID for a user. We don't need it because we are looking at overall trends, not individual people. It's also private.
*   `ip_address`: This tells us where a computer is located. It's also private and not needed for our general analysis.

In [5]:
print('Here are the fields we are working with:')
display(schema_df)

Here are the fields we are working with:

                  column_name  data_type
0                        date       DATE
1                search_query     STRING
2                 device_type     STRING
3                country_code     STRING
4           total_impressions      INT64
5                total_clicks      INT64
6          click_through_rate    FLOAT64
7             conversion_rate    FLOAT64
8          query_length_chars      INT64
9          num_words_in_query      INT64
10           time_of_day_hour      INT64
11                day_of_week      INT64
12  search_volume_last_7_days      INT64
13             query_category     STRING
14               user_id_hash     STRING
15                 ip_address     STRING
16          raw_log_timestamp  TIMESTAMP
17          total_conversions      INT64

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [6]:
print('--- Verifying Grain ---')
# We check if each row is unique based on our defined grain.
# If 'distinct_grain_combinations' equals 'total_rows', our grain is unique.
print(f"Total rows: {results_df['total_rows'].iloc[0]}")
print(f"Distinct grain combinations: {results_df['distinct_grain_combinations'].iloc[0]}")
print(f"Is grain unique? {results_df['total_rows'].iloc[0] == results_df['distinct_grain_combinations'].iloc[0]}")

print('\n--- Verifying Counts ---')
print(f"Total number of records in the data: {results_df['total_rows'].iloc[0]}")

print('\n--- Verifying Missing Values ---')
# In a real dataset, we would run code like 'df.isnull().sum()' to check for missing values.
# Since we only have the schema, we'll note that these important columns would be checked:
important_columns = ['search_query', 'total_impressions', 'date']
print(f"We would check for missing values in these key columns: {important_columns}")
print("Based on the schema, their types are:")
display(schema_df[schema_df['column_name'].isin(important_columns)])

print('\n--- Verifying Time Windows ---')
print(f"Start date of data: {results_df['min_date'].iloc[0].strftime('%Y-%m-%d')}")
print(f"End date of data: {results_df['max_date'].iloc[0].strftime('%Y-%m-%d')}")

--- Verifying Grain ---
Total rows: 10000
Distinct grain combinations: 10000
Is grain unique? True

--- Verifying Counts ---
Total number of records in the data: 10000

--- Verifying Missing Values ---
We would check for missing values in these key columns: ['search_query', 'total_impressions', 'date']
Based on the schema, their types are:

         column_name data_type
0               date      DATE
1       search_query    STRING
4  total_impressions     INT64

--- Verifying Time Windows ---
Start date of data: 2023-01-01
End date of data: 2023-01-31

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

This dataset has some limitations:

*   **Short Timeframe**: It only covers January 2023. This means we can't see how search behavior changes over seasons, holidays, or longer periods throughout the year.
*   **Search-Only Data**: The data only focuses on search queries. It doesn't tell us about other ways users might find information or interact with a product, like social media, direct website visits, or email marketing.
*   **No Personal Identifiers**: Because `user_id_hash` and `ip_address` are excluded for privacy, we can't track individual user journeys or understand personalized search trends.
*   **Specific Geographical Coverage**: The data might only cover certain regions or countries, so it may not represent global search behavior.

In [7]:
print('A key limitation is the time window covered by the data.')
print(f"The data covers a period of {(results_df['max_date'].iloc[0] - results_df['min_date'].iloc[0]).days + 1} days.")

A key limitation is the time window covered by the data.
The data covers a period of 31 days.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.